## 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that you can import into your Python projects to use its functionality without having to write the code from scratch. Libraries are designed to handle specific tasks or provide a set of related tools, which makes development faster and easier.

Why Do We Use Python Libraries?
Efficiency: Libraries save time by providing pre-written and tested code for common tasks, so you don't have to reinvent the wheel.

Complexity Management: They handle complex tasks (e.g., machine learning, data visualization) that would be difficult to implement on your own.

Consistency: Using libraries ensures that your code adheres to standard practices and reduces the likelihood of errors.

Community Support: Popular libraries are often well-documented and supported by large communities, making it easier to find help and resources.

Focus on Core Logic: By using libraries, you can focus on solving the main problem rather than spending time on lower-level coding tasks.

## 2. What is the difference between Numpy array and List?

Python provides both lists and NumPy arrays for handling collections of data, but they have key differences:

1. Data Type Flexibility
List: Can contain elements of different data types (e.g., integers, floats, strings, objects) within the same list.
Example: [1, 2.5, 'hello', [3, 4]]
NumPy Array: Designed for numerical computations, it requires all elements to be of the same data type. When you create a NumPy array, it will automatically convert all elements to a compatible data type.
Example: np.array([1, 2, 3.5]) will result in an array of floats: array([1.0, 2.0, 3.5])
2. Performance
List: Generally slower for numerical operations because they are not optimized for large-scale numerical computations.
NumPy Array: Much faster for numerical computations because they are implemented in C and use contiguous memory blocks, which allows for efficient vectorized operations.
3. Functionality
List: Basic data structure with standard operations like append, insert, and remove. They are versatile but lack advanced mathematical operations.
NumPy Array: Provides a wide range of mathematical and statistical functions, such as element-wise operations, broadcasting, and linear algebra operations.
4. Memory Efficiency
List: Less memory-efficient because it stores references to objects, which can lead to overhead when handling large datasets.
NumPy Array: More memory-efficient as it stores elements in a contiguous block of memory, reducing the overhead.
5. Multidimensional Support

## 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

For the given array:

- **Shape**: `(3, 4)` — The array has 3 rows and 4 columns.
- **Size**: `12` — The total number of elements in the array.
- **Dimension**: `2` — The array is 2-dimensional.

## 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Accessing the first row
first_row = array[0]

# Output the first row
print(first_row)


[1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Accessing the element at the third row and fourth column
element = array[2, 3]

# Output the element
print(element)


12


## 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extracting odd-indexed elements (considering 1-based index for clarity)
odd_elements = array[:, 1::2]

# Output the result
print(odd_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [4]:
import numpy as np

# Generating a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

# Output the random matrix
print(random_matrix)


[[0.8028761  0.961977   0.18497263]
 [0.9912916  0.1477958  0.37974748]
 [0.16001038 0.65404952 0.63675721]]


## 8. Describe the difference between np.random.rand and np.random.randn?

. Distribution
np.random.rand: Generates numbers from a uniform distribution (all numbers between 0 and 1 have an equal chance of being chosen).
np.random.randn: Generates numbers from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1.
2. Range
np.random.rand: The generated numbers are always between 0 and 1.
np.random.randn: The generated numbers typically fall between -3 and 3, but can be any real number.
3. Use Cases
np.random.rand: Used when you need random numbers within a uniform range (e.g., simulating dice rolls, generating probabilities).
np.random.randn: Used when you need random numbers that follow a normal distribution (e.g., in statistical modeling, machine learning).

## 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

# Original array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Add an extra dimension
expanded_array = np.expand_dims(array, axis=0)  # Adds a new axis at position 0

print("Original Array Shape:", array.shape)
print("Expanded Array Shape:", expanded_array.shape)
print("Expanded Array:")
print(expanded_array)


Original Array Shape: (3, 4)
Expanded Array Shape: (1, 3, 4)
Expanded Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


## 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np

# Original array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array
transposed_array = array.T  # Using the .T attribute

# Alternatively, you can use np.transpose()
# transposed_array = np.transpose(array)

print("Original Array:")
print(array)
print("Transposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order of an array is .byteswap(). This function changes the byte order of the array's elements, which is useful for handling data that might have been saved or transmitted in a different byte order.

## 14. What does the np.reshape function do, and how is it used?


In [ ]:
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new view of the array with the specified shape, as long as the new shape is compatible with the original shape (i.e., the total number of elements must be the same).